site_name: Mini C Compiler to Calango
theme:
  name: material
  language: pt-BR
  palette: 

    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - search.suggest 
    - content.code.copy 

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.highlight: # Adicione isso para garantir o controle dos blocos
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences: # Melhora a renderização dos blocos de código
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Gerenciamento:
    - Atas de Reunião:
      - Ata 15/04/26: gerenciamento/atas-de-reuniao/ata-15-04.md
    - Abordagem de desenvolvimento: gerenciamento/abordagem-desenvolvimento.md
    - Planejamento de sprints: gerenciamento/planejamento-de-sprints.md
  - Escopo do Projeto: escopo.md
  - Decisões técnicas: decisoes-tecnicas.md
  - Analisador Léxico: analisador-lexico.md
  - Analisador Sintático: analisador-sintatico.md
  - Problemas e soluções encontrados: problemas-e-solucoes-encontrados.md

extra_css:
  - stylesheets/extra.css